### ISSUE TITLE
Nodejs support

### ISSUE THREAD

**Issue by BenSayers** [DiUS/pact-consumer-js-dsl#15]
My team is interested in using Pact for some of our nodejs services and are looking options as to how we might go about this. Some of the options being explored:
- Add nodejs support to this library. Upon first inspection this appears to largely involve the use of XMLHttpRequest inside mockService.js.
- Create a new library very similar to this one - pact-consumer-nodejs-dsl
- Expand [pactjs0](https://github.com/DiUS/pactjs0) to be a full pact implementation.

I am interested in getting your thoughts and feedback before I dive in and start working on a solution.

Cheers,
Ben

**Comment by bethesque** [comment]
Sorry, I refactored the things :(
