### ISSUE TITLE
pactDir missing from the /pact POST request

### ISSUE THREAD

**Issue by mboudreau** [DiUS/pact-consumer-js-dsl#28]
This was available before, but seems to have been removed, even though the pact-mock-service still supports it.  Any reason why?

**Comment by bethesque** [comment]
It is now specified in the mock service command line `--pact-dir pacts`. It was a bad design decision to put it in the /pact post request.

**Comment by bethesque** [comment]
Sorry for API breakages. It's still under a lot of flux. Hence the warning on the README!
