### ISSUE TITLE
Adding SomethingLike and Term into the DSL

### ISSUE THREAD

**Issue by mboudreau** [DiUS/pact-consumer-js-dsl#33]
Since we've talked about it in the last PR, this should be something added to the DSL for the sake of simplicity.  I'm not sure where it should go however.  Pact.Term?  Pact.Utils.Term/SomethingLike?

**Comment by bethesque** [comment]
Sorry, I never saw this comment!

**Comment by bethesque** [comment]
@k-ong : https://github.com/DiUS/pact-consumer-js-dsl/wiki/Flexible-matching
