### ISSUE TITLE
Is using Jasmine a requirement?

### ISSUE THREAD

**Issue by moroshko** [DiUS/pact-consumer-js-dsl#35]
In the docs you say: 

> Answer **jasmine** for testing framework...

Is that possible to use **mocha** or any other framework?

**Comment by bethesque** [comment]
We haven't tried! I can't think of a reason it shouldn't work, we tried very hard to make it not jasmine specific (though we did start just making it work with Jasmine, so that comment is probably just left over).

**Comment by moroshko** [comment]
@bethesque Thanks for the quick answer! I'll try and let you know :)

**Comment by moroshko** [comment]
Things look ok with mocha :)
