### ISSUE TITLE
Where ProviderClient and MockService are defined?

### ISSUE THREAD

**Issue by moroshko** [DiUS/pact-consumer-js-dsl#36]
Docs have the following snippet:
```
beforeEach(function() {
    client = new ProviderClient('http://localhost:1234');
    helloProvider = MockService.create({
```
* Where is `ProviderClient` defined?
* Is `MockService` supposed to be `Pact.MockService`?

**Comment by bethesque** [comment]
https://github.com/DiUS/pact-consumer-js-dsl/commit/01114d6849ec25d39e68354f20fa5b5b2e5f0f52

**Comment by bethesque** [comment]
Please see amended README.

**Comment by moroshko** [comment]
Thanks for the quick response!
