### ISSUE TITLE
Link to Pact README in project README broken

### ISSUE THREAD

**Issue by timoreimann** [DiUS/pact-consumer-js-dsl#47]
The [first paragraph of the README file](https://github.com/DiUS/pact-consumer-js-dsl/blob/master/README.md#pact-consumer-javascript-dsl) suggest to

> please read the Pact [README](https://github.com/DiUS/pact-consumer-js-dsl/blob/master/pact-readme) first.

Unfortunately, the link is broken (404).

**Comment by bethesque** [comment]
Thanks, fixed.
